In [1]:
import pandas as pd

In [5]:
data=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv")

In [7]:
# data

# HOw to write pandas files

- Columns(Columns)

- nrows(U can call diserbale rows)

- usecols(use normal as well as index)

- Skiprows(use normal as well as index)

- Index_col(Use to create a index of particular col)

- header

- Prefix

- Names

In [8]:
data.columns

Index(['Student Code', 'Degree', 'Student_Name', 'Mid', 'Quiz 1', 'Quiz 2',
       'Best of Quizzes', 'Assignment 1', 'Assignment 2',
       'Best of Assignments', 'Total Sessional (50)', 'Final (50)',
       'Total (100)', 'Grade'],
      dtype='object')

# nrows

In [13]:
data=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",nrows=2)
data

,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3,8,7,9,9,45,25,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5,5,8,10,10,32,18,50,F

# Usecols

In [20]:
data_col=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",usecols=[2])
data_col

                      Student_Name
0                      Abdul Basit
1                      Adeel Ahmed
2                     Afrah Zareen
3                   Ahmed Ali Raza
4                  Ahsan Ali Vohra
5                      Ameer Hamza
6                    Anas Ali Khan
7                 Aneebullah Niazi
8                   Areesha Sohail
9                          Arsalan
10             Fatima Haider Warsi
11                     Habib Ullah
12             Hafiza Tooba Akbani
13              Hamza Abdul Jabbar
14                   Hareem Afshan
15                    Haseeb Sajid
16                    Hassam Ahmed
17                    Khalid Anwer
18                   Madiha Jabeen
19                 Mohammad Hunain
20                  Muhammad Aamir
21  Muhammad Abdul Rehman Siddiqui
22               Muhammad Abdullah
23              Muhammad Ali Iqbal
24                  Muhammad Bilal
25                  Muhammad Faraz
26         Muhammad Ghazali Faridi
27             Muhammad Osama Khan
28          Muhammad Saqib Intizar
29       Muhammad Shahroz Khurshid
30                 Muhammad Shozab
31           Muhammad Taha Hasnain
32           Muhammad Wajahat Khan
33            Muhammad Younus Baig
34                Nazeer Bin Zafar
35                      Rabi Ahmed
36                      Rida Nasim
37                   Sadaf Nosheen
38                Sadaquat Rafique
39                     Sania Iqbal
40                     Sharif Taqi
41                   Shariqa Ahmad
42                   Sumbul Rehman
43               Syed Faizan Uddin
44                     Syed Sohaib
45               Syeda Sabika Raza
46                      Usman Khan
47                     Waqar Ahmed

In [26]:
data_col_rows=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",usecols=[2],nrows=3)
data_col_rows

   Student_Name
0   Abdul Basit
1   Adeel Ahmed
2  Afrah Zareen

# Skiprows

In [51]:
data_col_rows=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",skiprows=1)
data_col_rows

,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

# Index_col

In [52]:
data_col_rows=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",index_col="Student_Name")
data_col_rows

ValueError: Index Student_Name invalid

In [53]:
data_col_rows=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",index_col=[5])
data_col_rows

,1,2,3,4,5,7,8,9,10,11,12,13,14
6,,,,,,,,,,,,,
Quiz 2,Student Code,Degree,Student_Name,Mid,Quiz 1,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
3,022-14-19987,BS(CS),Abdul Basit,28,8,8,7,9,9,45,25,70,B
5,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5,8,10,10,32,18,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5,5,8,10,10,33,30,63,C
2,022-14-19718,BS(CS),Ahmed Ali Raza,14,7,7,NaN,2,2,23,23,46,F
6,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7,7,7,9,9,43,34,77,B
6,022-14-110232,BS(CS),Ameer Hamza,25,9,9,8,10,10,44,27,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5,6,8,10,10,44,30,74,B
6,022-14-110388,BS(CS),Aneebullah Niazi,26,9,9,8,10,10,45,40,85,A
4,022-14-110601,BS(CS),Areesha Sohail,19,9,9,7,9,9,37,24,61,C
6,022-14-110599,BS(CS),Arsalan,28,8,8,8,NaN,8,44,40,84,A
7,022-14-110214,BS(CS),Fatima Haider Warsi,30,8,8,8,NaN,8,46,45,91,A
5,022-14-110591,BS(CS),Habib Ullah,28,8,8,5,NaN,5,41,35,76,B
5,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7,7,8,10,10,40,33,73,B
4,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8,8,8,10,10,42,25,67,C
4,022-14-110389,BS(CS),Hareem Afshan,21,7,7,6,8,8,36,29,65,C
NaN,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,0,NaN,NaN,0,18,NaN,18,F
5,022-14-110596,BS(CS),Hassam Ahmed,23,5,5,7,9,9,37,35,72,B
5,022-14-110396,BS(CS),Khalid Anwer,20,8,8,9,11,11,39,31,70,B
2,022-14-110223,BS(CS),Madiha Jabeen,16,5,5,8,10,10,31,29,60,C
6,022-14-110222,BS(CS),Mohammad Hunain,27,9,9,8,10,10,46,45,91,A
6,022-14-110412,BS(CS),Muhammad Aamir,24,7,7,7,9,9,40,31,71,B
6,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9,9,9,11,11,40,20,60,C
6,022-14-110398,BS(CS),Muhammad Abdullah,20,7,7,7,NaN,7,34,23,57,F
NaN,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5,5,8,10,10,41,21,62,C
4,022-14-110215,BS(CS),Muhammad Bilal,28,5,5,9,11,11,44,33,77,B
6,022-14-110105,BS(CS),Muhammad Faraz,26,9,9,8,10,10,45,41,86,A
NaN,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6,6,6,8,8,41,24,65,C
6,022-14-110452,BS(CS),Muhammad Osama Khan,27,8,8,8,10,10,45,26,71,B
6,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6,6,9,11,11,39,18,57,F
1,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7,7,6,NaN,6,30,9,39,F
6,022-14-110401,BS(CS),Muhammad Shozab,23,8,8,9,NaN,9,40,32,72,B
5,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7,7,10,NaN,10,44,29,73,B
2,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2,8,10,10,21,8,29,F
2,022-14-19919,BS(CS),Muhammad Younus Baig,20,4,4,8,10,10,34,17,51,F
6,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9,9,8,10,10,44,42,86,A
5,022-14-19923,BS(CS),Rabi Ahmed,20,8,8,NaN,10,10,38,28,66,C
5,022-14-110582,BS(CS),Rida Nasim,25,9,9,9,NaN,9,43,27,70,B
5,022-14-110230,BS(CS),Sadaf Nosheen,27,9,9,9,NaN,9,45,30,75,B
6,022-14-110229,BS(CS),Sadaquat Rafique,9,6,6,5,7,7,22,17,39,F
4,022-14-110107,BS(CS),Sania Iqbal,28,4,4,9,11,11,43,25,68,C
6,022-14-110584,BS(CS),Sharif Taqi,27,9,9,8,10,10,46,35,81,A
6,022-14-110225,BS(CS),Shariqa Ahmad,20,7,7,8,10,10,37,20,57,F
6,022-14-110587,BS(CS),Sumbul Rehman,28,5,6,8,10,10,44,23,67,C
4,022-14-110451,BS(CS),Syed Faizan Uddin,28,9,9,6,8,8,45,34,79,B
5,022-14-110589,BS(CS),Syed Sohaib,25,7,7,9,NaN,9,41,22,63,C
6,022-14-110400,BS(CS),Syeda Sabika Raza,27,9,9,9,NaN,9,45,35,80,A
5,022-14-19911,BS(CS),Usman Khan,25,8,8,8,10,10,43,22,65,C
5,022-14-110219,BS(CS),Waqar Ahmed,11,9,9,5,7,7,27,19,46,F

# Header

In [55]:
data_header=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",header=1)
data_header

,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [56]:
data_header=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",header=None)
data_header

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
1,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
2,022-14-19987,BS(CS),Abdul Basit,28,8,3,8,7,9,9,45,25,70,B
3,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5,5,8,10,10,32,18,50,F
4,022-14-110585,BS(CS),Afrah Zareen,18,5,2,5,8,10,10,33,30,63,C
5,022-14-19718,BS(CS),Ahmed Ali Raza,14,7,2,7,NaN,2,2,23,23,46,F
6,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7,6,7,7,9,9,43,34,77,B
7,022-14-110232,BS(CS),Ameer Hamza,25,9,6,9,8,10,10,44,27,71,B
8,022-14-110588,BS(CS),Anas Ali Khan,28,5,6,6,8,10,10,44,30,74,B
9,022-14-110388,BS(CS),Aneebullah Niazi,26,9,6,9,8,10,10,45,40,85,A
10,022-14-110601,BS(CS),Areesha Sohail,19,9,4,9,7,9,9,37,24,61,C
11,022-14-110599,BS(CS),Arsalan,28,8,6,8,8,NaN,8,44,40,84,A
12,022-14-110214,BS(CS),Fatima Haider Warsi,30,8,7,8,8,NaN,8,46,45,91,A
13,022-14-110591,BS(CS),Habib Ullah,28,8,5,8,5,NaN,5,41,35,76,B
14,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7,5,7,8,10,10,40,33,73,B
15,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8,4,8,8,10,10,42,25,67,C
16,022-14-110389,BS(CS),Hareem Afshan,21,7,4,7,6,8,8,36,29,65,C
17,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
18,022-14-110596,BS(CS),Hassam Ahmed,23,5,5,5,7,9,9,37,35,72,B
19,022-14-110396,BS(CS),Khalid Anwer,20,8,5,8,9,11,11,39,31,70,B
20,022-14-110223,BS(CS),Madiha Jabeen,16,5,2,5,8,10,10,31,29,60,C
21,022-14-110222,BS(CS),Mohammad Hunain,27,9,6,9,8,10,10,46,45,91,A
22,022-14-110412,BS(CS),Muhammad Aamir,24,7,6,7,7,9,9,40,31,71,B
23,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9,6,9,9,11,11,40,20,60,C
24,022-14-110398,BS(CS),Muhammad Abdullah,20,7,6,7,7,NaN,7,34,23,57,F
25,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5,NaN,5,8,10,10,41,21,62,C
26,022-14-110215,BS(CS),Muhammad Bilal,28,5,4,5,9,11,11,44,33,77,B
27,022-14-110105,BS(CS),Muhammad Faraz,26,9,6,9,8,10,10,45,41,86,A
28,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6,NaN,6,6,8,8,41,24,65,C
29,022-14-110452,BS(CS),Muhammad Osama Khan,27,8,6,8,8,10,10,45,26,71,B
30,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6,6,6,9,11,11,39,18,57,F
31,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7,1,7,6,NaN,6,30,9,39,F
32,022-14-110401,BS(CS),Muhammad Shozab,23,8,6,8,9,NaN,9,40,32,72,B
33,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7,5,7,10,NaN,10,44,29,73,B
34,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2,2,8,10,10,21,8,29,F
35,022-14-19919,BS(CS),Muhammad Younus Baig,20,4,2,4,8,10,10,34,17,51,F
36,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9,6,9,8,10,10,44,42,86,A
37,022-14-19923,BS(CS),Rabi Ahmed,20,8,5,8,NaN,10,10,38,28,66,C
38,022-14-110582,BS(CS),Rida Nasim,25,9,5,9,9,NaN,9,43,27,70,B
39,022-14-110230,BS(CS),Sadaf Nosheen,27,9,5,9,9,NaN,9,45,30,75,B
40,022-14-110229,BS(CS),Sadaquat Rafique,9,6,6,6,5,7,7,22,17,39,F
41,022-14-110107,BS(CS),Sania Iqbal,28,4,4,4,9,11,11,43,25,68,C
42,022-14-110584,BS(CS),Sharif Taqi,27,9,6,9,8,10,10,46,35,81,A
43,022-14-110225,BS(CS),Shariqa Ahmad,20,7,6,7,8,10,10,37,20,57,F
44,022-14-110587,BS(CS),Sumbul Rehman,28,5,6,6,8,10,10,44,23,67,C
45,022-14-110451,BS(CS),Syed Faizan Uddin,28,9,4,9,6,8,8,45,34,79,B
46,022-14-110589,BS(CS),Syed Sohaib,25,7,5,7,9,NaN,9,41,22,63,C
47,022-14-110400,BS(CS),Syeda Sabika Raza,27,9,6,9,9,NaN,9,45,35,80,A
48,022-14-19911,BS(CS),Usman Khan,25,8,5,8,8,10,10,43,22,65,C
49,022-14-110219,BS(CS),Waqar Ahmed,11,9,5,9,5,7,7,27,19,46,F

# Prefix

In [57]:
data_prefix=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",header=None,prefix="columns")
data_prefix

,columns0,columns1,columns2,columns3,columns4,columns5,columns6,columns7,columns8,columns9,columns10,columns11,columns12,columns13
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
1,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
2,022-14-19987,BS(CS),Abdul Basit,28,8,3,8,7,9,9,45,25,70,B
3,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5,5,8,10,10,32,18,50,F
4,022-14-110585,BS(CS),Afrah Zareen,18,5,2,5,8,10,10,33,30,63,C
5,022-14-19718,BS(CS),Ahmed Ali Raza,14,7,2,7,NaN,2,2,23,23,46,F
6,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7,6,7,7,9,9,43,34,77,B
7,022-14-110232,BS(CS),Ameer Hamza,25,9,6,9,8,10,10,44,27,71,B
8,022-14-110588,BS(CS),Anas Ali Khan,28,5,6,6,8,10,10,44,30,74,B
9,022-14-110388,BS(CS),Aneebullah Niazi,26,9,6,9,8,10,10,45,40,85,A
10,022-14-110601,BS(CS),Areesha Sohail,19,9,4,9,7,9,9,37,24,61,C
11,022-14-110599,BS(CS),Arsalan,28,8,6,8,8,NaN,8,44,40,84,A
12,022-14-110214,BS(CS),Fatima Haider Warsi,30,8,7,8,8,NaN,8,46,45,91,A
13,022-14-110591,BS(CS),Habib Ullah,28,8,5,8,5,NaN,5,41,35,76,B
14,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7,5,7,8,10,10,40,33,73,B
15,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8,4,8,8,10,10,42,25,67,C
16,022-14-110389,BS(CS),Hareem Afshan,21,7,4,7,6,8,8,36,29,65,C
17,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
18,022-14-110596,BS(CS),Hassam Ahmed,23,5,5,5,7,9,9,37,35,72,B
19,022-14-110396,BS(CS),Khalid Anwer,20,8,5,8,9,11,11,39,31,70,B
20,022-14-110223,BS(CS),Madiha Jabeen,16,5,2,5,8,10,10,31,29,60,C
21,022-14-110222,BS(CS),Mohammad Hunain,27,9,6,9,8,10,10,46,45,91,A
22,022-14-110412,BS(CS),Muhammad Aamir,24,7,6,7,7,9,9,40,31,71,B
23,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9,6,9,9,11,11,40,20,60,C
24,022-14-110398,BS(CS),Muhammad Abdullah,20,7,6,7,7,NaN,7,34,23,57,F
25,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5,NaN,5,8,10,10,41,21,62,C
26,022-14-110215,BS(CS),Muhammad Bilal,28,5,4,5,9,11,11,44,33,77,B
27,022-14-110105,BS(CS),Muhammad Faraz,26,9,6,9,8,10,10,45,41,86,A
28,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6,NaN,6,6,8,8,41,24,65,C
29,022-14-110452,BS(CS),Muhammad Osama Khan,27,8,6,8,8,10,10,45,26,71,B
30,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6,6,6,9,11,11,39,18,57,F
31,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7,1,7,6,NaN,6,30,9,39,F
32,022-14-110401,BS(CS),Muhammad Shozab,23,8,6,8,9,NaN,9,40,32,72,B
33,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7,5,7,10,NaN,10,44,29,73,B
34,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2,2,8,10,10,21,8,29,F
35,022-14-19919,BS(CS),Muhammad Younus Baig,20,4,2,4,8,10,10,34,17,51,F
36,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9,6,9,8,10,10,44,42,86,A
37,022-14-19923,BS(CS),Rabi Ahmed,20,8,5,8,NaN,10,10,38,28,66,C
38,022-14-110582,BS(CS),Rida Nasim,25,9,5,9,9,NaN,9,43,27,70,B
39,022-14-110230,BS(CS),Sadaf Nosheen,27,9,5,9,9,NaN,9,45,30,75,B
40,022-14-110229,BS(CS),Sadaquat Rafique,9,6,6,6,5,7,7,22,17,39,F
41,022-14-110107,BS(CS),Sania Iqbal,28,4,4,4,9,11,11,43,25,68,C
42,022-14-110584,BS(CS),Sharif Taqi,27,9,6,9,8,10,10,46,35,81,A
43,022-14-110225,BS(CS),Shariqa Ahmad,20,7,6,7,8,10,10,37,20,57,F
44,022-14-110587,BS(CS),Sumbul Rehman,28,5,6,6,8,10,10,44,23,67,C
45,022-14-110451,BS(CS),Syed Faizan Uddin,28,9,4,9,6,8,8,45,34,79,B
46,022-14-110589,BS(CS),Syed Sohaib,25,7,5,7,9,NaN,9,41,22,63,C
47,022-14-110400,BS(CS),Syeda Sabika Raza,27,9,6,9,9,NaN,9,45,35,80,A
48,022-14-19911,BS(CS),Usman Khan,25,8,5,8,8,10,10,43,22,65,C
49,022-14-110219,BS(CS),Waqar Ahmed,11,9,5,9,5,7,7,27,19,46,F

In [58]:
data_prefix=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",header=None,prefix="Data")
data_prefix

,Data0,Data1,Data2,Data3,Data4,Data5,Data6,Data7,Data8,Data9,Data10,Data11,Data12,Data13
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
1,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
2,022-14-19987,BS(CS),Abdul Basit,28,8,3,8,7,9,9,45,25,70,B
3,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5,5,8,10,10,32,18,50,F
4,022-14-110585,BS(CS),Afrah Zareen,18,5,2,5,8,10,10,33,30,63,C
5,022-14-19718,BS(CS),Ahmed Ali Raza,14,7,2,7,NaN,2,2,23,23,46,F
6,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7,6,7,7,9,9,43,34,77,B
7,022-14-110232,BS(CS),Ameer Hamza,25,9,6,9,8,10,10,44,27,71,B
8,022-14-110588,BS(CS),Anas Ali Khan,28,5,6,6,8,10,10,44,30,74,B
9,022-14-110388,BS(CS),Aneebullah Niazi,26,9,6,9,8,10,10,45,40,85,A
10,022-14-110601,BS(CS),Areesha Sohail,19,9,4,9,7,9,9,37,24,61,C
11,022-14-110599,BS(CS),Arsalan,28,8,6,8,8,NaN,8,44,40,84,A
12,022-14-110214,BS(CS),Fatima Haider Warsi,30,8,7,8,8,NaN,8,46,45,91,A
13,022-14-110591,BS(CS),Habib Ullah,28,8,5,8,5,NaN,5,41,35,76,B
14,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7,5,7,8,10,10,40,33,73,B
15,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8,4,8,8,10,10,42,25,67,C
16,022-14-110389,BS(CS),Hareem Afshan,21,7,4,7,6,8,8,36,29,65,C
17,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
18,022-14-110596,BS(CS),Hassam Ahmed,23,5,5,5,7,9,9,37,35,72,B
19,022-14-110396,BS(CS),Khalid Anwer,20,8,5,8,9,11,11,39,31,70,B
20,022-14-110223,BS(CS),Madiha Jabeen,16,5,2,5,8,10,10,31,29,60,C
21,022-14-110222,BS(CS),Mohammad Hunain,27,9,6,9,8,10,10,46,45,91,A
22,022-14-110412,BS(CS),Muhammad Aamir,24,7,6,7,7,9,9,40,31,71,B
23,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9,6,9,9,11,11,40,20,60,C
24,022-14-110398,BS(CS),Muhammad Abdullah,20,7,6,7,7,NaN,7,34,23,57,F
25,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5,NaN,5,8,10,10,41,21,62,C
26,022-14-110215,BS(CS),Muhammad Bilal,28,5,4,5,9,11,11,44,33,77,B
27,022-14-110105,BS(CS),Muhammad Faraz,26,9,6,9,8,10,10,45,41,86,A
28,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6,NaN,6,6,8,8,41,24,65,C
29,022-14-110452,BS(CS),Muhammad Osama Khan,27,8,6,8,8,10,10,45,26,71,B
30,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6,6,6,9,11,11,39,18,57,F
31,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7,1,7,6,NaN,6,30,9,39,F
32,022-14-110401,BS(CS),Muhammad Shozab,23,8,6,8,9,NaN,9,40,32,72,B
33,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7,5,7,10,NaN,10,44,29,73,B
34,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2,2,8,10,10,21,8,29,F
35,022-14-19919,BS(CS),Muhammad Younus Baig,20,4,2,4,8,10,10,34,17,51,F
36,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9,6,9,8,10,10,44,42,86,A
37,022-14-19923,BS(CS),Rabi Ahmed,20,8,5,8,NaN,10,10,38,28,66,C
38,022-14-110582,BS(CS),Rida Nasim,25,9,5,9,9,NaN,9,43,27,70,B
39,022-14-110230,BS(CS),Sadaf Nosheen,27,9,5,9,9,NaN,9,45,30,75,B
40,022-14-110229,BS(CS),Sadaquat Rafique,9,6,6,6,5,7,7,22,17,39,F
41,022-14-110107,BS(CS),Sania Iqbal,28,4,4,4,9,11,11,43,25,68,C
42,022-14-110584,BS(CS),Sharif Taqi,27,9,6,9,8,10,10,46,35,81,A
43,022-14-110225,BS(CS),Shariqa Ahmad,20,7,6,7,8,10,10,37,20,57,F
44,022-14-110587,BS(CS),Sumbul Rehman,28,5,6,6,8,10,10,44,23,67,C
45,022-14-110451,BS(CS),Syed Faizan Uddin,28,9,4,9,6,8,8,45,34,79,B
46,022-14-110589,BS(CS),Syed Sohaib,25,7,5,7,9,NaN,9,41,22,63,C
47,022-14-110400,BS(CS),Syeda Sabika Raza,27,9,6,9,9,NaN,9,45,35,80,A
48,022-14-19911,BS(CS),Usman Khan,25,8,5,8,8,10,10,43,22,65,C
49,022-14-110219,BS(CS),Waqar Ahmed,11,9,5,9,5,7,7,27,19,46,F

# Names

In [59]:
data_Name=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",header=None,names=["ID","B","C","D","E","F","G","H","I","j","K","L","M","N"])
data_Name

,ID,B,C,D,E,F,G,H,I,j,K,L,M,N
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
1,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
2,022-14-19987,BS(CS),Abdul Basit,28,8,3,8,7,9,9,45,25,70,B
3,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5,5,8,10,10,32,18,50,F
4,022-14-110585,BS(CS),Afrah Zareen,18,5,2,5,8,10,10,33,30,63,C
5,022-14-19718,BS(CS),Ahmed Ali Raza,14,7,2,7,NaN,2,2,23,23,46,F
6,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7,6,7,7,9,9,43,34,77,B
7,022-14-110232,BS(CS),Ameer Hamza,25,9,6,9,8,10,10,44,27,71,B
8,022-14-110588,BS(CS),Anas Ali Khan,28,5,6,6,8,10,10,44,30,74,B
9,022-14-110388,BS(CS),Aneebullah Niazi,26,9,6,9,8,10,10,45,40,85,A
10,022-14-110601,BS(CS),Areesha Sohail,19,9,4,9,7,9,9,37,24,61,C
11,022-14-110599,BS(CS),Arsalan,28,8,6,8,8,NaN,8,44,40,84,A
12,022-14-110214,BS(CS),Fatima Haider Warsi,30,8,7,8,8,NaN,8,46,45,91,A
13,022-14-110591,BS(CS),Habib Ullah,28,8,5,8,5,NaN,5,41,35,76,B
14,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7,5,7,8,10,10,40,33,73,B
15,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8,4,8,8,10,10,42,25,67,C
16,022-14-110389,BS(CS),Hareem Afshan,21,7,4,7,6,8,8,36,29,65,C
17,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
18,022-14-110596,BS(CS),Hassam Ahmed,23,5,5,5,7,9,9,37,35,72,B
19,022-14-110396,BS(CS),Khalid Anwer,20,8,5,8,9,11,11,39,31,70,B
20,022-14-110223,BS(CS),Madiha Jabeen,16,5,2,5,8,10,10,31,29,60,C
21,022-14-110222,BS(CS),Mohammad Hunain,27,9,6,9,8,10,10,46,45,91,A
22,022-14-110412,BS(CS),Muhammad Aamir,24,7,6,7,7,9,9,40,31,71,B
23,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9,6,9,9,11,11,40,20,60,C
24,022-14-110398,BS(CS),Muhammad Abdullah,20,7,6,7,7,NaN,7,34,23,57,F
25,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5,NaN,5,8,10,10,41,21,62,C
26,022-14-110215,BS(CS),Muhammad Bilal,28,5,4,5,9,11,11,44,33,77,B
27,022-14-110105,BS(CS),Muhammad Faraz,26,9,6,9,8,10,10,45,41,86,A
28,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6,NaN,6,6,8,8,41,24,65,C
29,022-14-110452,BS(CS),Muhammad Osama Khan,27,8,6,8,8,10,10,45,26,71,B
30,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6,6,6,9,11,11,39,18,57,F
31,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7,1,7,6,NaN,6,30,9,39,F
32,022-14-110401,BS(CS),Muhammad Shozab,23,8,6,8,9,NaN,9,40,32,72,B
33,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7,5,7,10,NaN,10,44,29,73,B
34,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2,2,8,10,10,21,8,29,F
35,022-14-19919,BS(CS),Muhammad Younus Baig,20,4,2,4,8,10,10,34,17,51,F
36,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9,6,9,8,10,10,44,42,86,A
37,022-14-19923,BS(CS),Rabi Ahmed,20,8,5,8,NaN,10,10,38,28,66,C
38,022-14-110582,BS(CS),Rida Nasim,25,9,5,9,9,NaN,9,43,27,70,B
39,022-14-110230,BS(CS),Sadaf Nosheen,27,9,5,9,9,NaN,9,45,30,75,B
40,022-14-110229,BS(CS),Sadaquat Rafique,9,6,6,6,5,7,7,22,17,39,F
41,022-14-110107,BS(CS),Sania Iqbal,28,4,4,4,9,11,11,43,25,68,C
42,022-14-110584,BS(CS),Sharif Taqi,27,9,6,9,8,10,10,46,35,81,A
43,022-14-110225,BS(CS),Shariqa Ahmad,20,7,6,7,8,10,10,37,20,57,F
44,022-14-110587,BS(CS),Sumbul Rehman,28,5,6,6,8,10,10,44,23,67,C
45,022-14-110451,BS(CS),Syed Faizan Uddin,28,9,4,9,6,8,8,45,34,79,B
46,022-14-110589,BS(CS),Syed Sohaib,25,7,5,7,9,NaN,9,41,22,63,C
47,022-14-110400,BS(CS),Syeda Sabika Raza,27,9,6,9,9,NaN,9,45,35,80,A
48,022-14-19911,BS(CS),Usman Khan,25,8,5,8,8,10,10,43,22,65,C
49,022-14-110219,BS(CS),Waqar Ahmed,11,9,5,9,5,7,7,27,19,46,F

# Head & tail

In [60]:
data_head=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",skiprows=1)
data_head.head(2)

,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F

In [61]:
data_tail=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",skiprows=1)
data_tail.tail(2)

,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

# dtype

In [62]:
data_dtype=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",skiprows=1,dtype={"Mid":"float64","Assignment2" :"int64"})
data_dtype

,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28.0,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17.0,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18.0,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14.0,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27.0,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25.0,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28.0,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26.0,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19.0,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28.0,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30.0,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
11,022-14-110591,BS(CS),Habib Ullah,28.0,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23.0,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24.0,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21.0,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Haseeb Sajid,18.0,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
16,022-14-110596,BS(CS),Hassam Ahmed,23.0,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20.0,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16.0,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27.0,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24.0,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20.0,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20.0,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26.0,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28.0,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26.0,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27.0,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27.0,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22.0,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17.0,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23.0,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27.0,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9.0,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20.0,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25.0,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20.0,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25.0,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27.0,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9.0,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28.0,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27.0,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20.0,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28.0,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28.0,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25.0,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27.0,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25.0,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11.0,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

# True_Values

In [79]:
data_f_values=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",true_values=["No"])
data_f_values

,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade,True_values,False_values
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B,yes,True
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F,yes,True
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C,yes,True
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F,yes,True
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B,yes,True
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B,yes,True
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B,yes,True
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A,yes,True
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C,yes,True
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A,yes,True
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A,yes,True
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B,yes,True
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B,yes,True
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C,yes,True
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C,yes,True
15,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F,yes,True
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B,yes,True
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B,yes,True
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C,yes,True
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A,yes,True
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B,yes,True
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C,yes,True
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F,yes,True
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C,yes,True
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B,yes,True
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A,yes,True
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C,yes,True
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B,yes,True
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F,yes,True
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F,yes,True
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B,yes,True
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B,yes,True
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F,yes,True
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F,yes,True
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A,yes,True
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C,yes,True
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B,yes,True
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B,yes,True
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F,yes,True
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C,yes,True
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A,yes,True
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F,yes,True
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C,yes,True
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B,yes,True
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C,yes,True
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A,yes,True
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C,yes,True
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F,yes,True

# False_Values

In [77]:
data_f_values=pd.read_csv("D:\\PIAIC DOC\\Q2\\pandas\\PRACTICE\\Read CSV\\data.csv",false_values=["no"])
data_f_values

,Student Code,Degree,Student_Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade,True_values,False_values
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B,yes,No
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F,yes,No
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C,yes,No
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F,yes,No
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B,yes,No
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B,yes,No
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B,yes,No
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A,yes,No
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C,yes,No
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A,yes,No
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A,yes,No
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B,yes,No
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B,yes,No
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C,yes,No
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C,yes,No
15,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F,yes,No
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B,yes,No
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B,yes,No
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C,yes,No
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A,yes,No
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B,yes,No
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C,yes,No
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F,yes,No
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C,yes,No
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B,yes,No
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A,yes,No
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C,yes,No
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B,yes,No
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F,yes,No
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F,yes,No
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B,yes,No
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B,yes,No
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F,yes,No
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F,yes,No
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A,yes,No
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C,yes,No
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B,yes,No
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B,yes,No
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F,yes,No
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C,yes,No
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A,yes,No
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F,yes,No
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C,yes,No
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B,yes,No
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C,yes,No
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A,yes,No
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C,yes,No
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F,yes,No

In [7]:
import numpy as np  
a = np.ones((2,3,4))  #2 rows hain dekh 3 coloumns and 4 coloumns values
# index     0  1  2


After_tranpose=np.transpose(a,(2,1,0)).shape  # is index p set kia hai  2 par upr 0 index hai jb k value 2 hai
#                                                  1 index p 3 and 2 index p 4 hai.
#   index                      4,3,2


print(After_tranpose)

(4, 3, 2)

In [26]:
data=np.arange(30).reshape(2,5,3)
print(data.shape)   # dekh reshape me jo index hai rows ka 0 hai coloumns ka 1 and values ka  2
# jb transpose kr lia
transpose_data=np.transpose(data,(1,0,2)).shape  # ab yhn dekho 1 pe 5 hai then 0 p 2 hai or 2 par 3 hai..
                                                #.hm ny khud rows coloums and vlaues ko change kr dya
print(transpose_data)

(2, 5, 3)
(5, 2, 3)

(5, 2, 3)